source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PlaygroundTesting_Example', :exclusive => true do
  pod 'PlaygroundTesting', :path => '../'
end

target 'PlaygroundTesting_Tests', :exclusive => true do
  pod 'PlaygroundTesting', :path => '../'

  pod 'Quick', '~> 0.9'
  # pod 'Nimble', '~> 3.1'
  pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git'
end
