# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
osx_image: xcode7.2
language: objective-c

before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - pod install --project-directory=Example

xcode_workspace: Example/PlaygroundTesting.xcworkspace
xcode_scheme: PlaygroundTesting-Example
xcode_sdk: iphonesimulator
